name: website-monitoring

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 2 * * *'

jobs:
  monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Checking websites status
        run: |
          chmod +x ./scripts/monitoring/alive.sh
          ./scripts/monitoring/alive.sh
        shell: bash
