name: website-monitoring

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 2 * * *'

jobs:
  monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checking websites status
        run: sh ./scripts/monitoring/alive.sh
